apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
  labels:
    type: local
spec:
  capacity:
    storage: 700Gi
  accessModes:
    # the volume can be mounted as read-write by many nodes
    - ReadWriteMany
    # Allow WaitForFirstConsumer
  storageClassName: local-storage
  local:
    path: /data/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - to-be-replaced
  claimRef:
    namespace: default
    name: downloads
