apiVersion: cert-manager.io/v1 
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: username@host.domain
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: public
# https://cert-manager.io/docs/tutorials/acme/ingress/