apiVersion: v1
kind: PersistentVolume
metadata:
  name: public
  labels:
    type: local
spec:
  capacity:
    storage: 500Gi
  accessModes:
    # the volume can be mounted as read-write by many nodes
    - ReadWriteMany
    # Allow WaitForFirstConsumer
  storageClassName: local-storage
  local:
    path: /data/public
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vincent
claimRef:
  namespace: default
  name: public
