apiVersion: v1
kind: LimitRange
metadata:
  name: res-limit-range
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 0.5
      defaultRequest:
        memory: 32Mi
        cpu: 0.1
      type: Container
