FROM vladgh/minidlna:v0.3.10

# https://hub.docker.com/r/vladgh/minidlna
# https://github.com/vladgh/docker_base_images/blob/master/minidlna/Dockerfile
# https://github.com/mytracks/readymedia/tree/a3dc7bf3067026f59410a30cc57471258f8236d5