apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slurp-lemonde-local
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    type: local
spec:
  rules:
    - host: slurp-lemonde.local
      http:
        paths:
          - backend:
              service:
                name: slurp-lemonde
                port:
                  number: 3000
            path: /
            pathType: Prefix
