apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify-local
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    type: local
spec:
  rules:
    - host: gotify.local
      http:
        paths:
          - backend:
              service:
                name: gotify
                port:
                  number: 3000
            path: /
            pathType: Prefix
