apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify-ext

  labels:
    type: external
spec:
  tls:
    - hosts:
        - gotify.former-hostname.com
      secretName: gotify.former-hostname.com
  rules:
    - host: gotify.former-hostname.com
      http:
        paths:
          - backend:
              service:
                name: gotify
                port:
                  number: 3000
            path: /
            pathType: Prefix
