apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify-ext

  labels:
    type: external
spec:
  tls:
    - hosts:
        - gotify.{hostname}
      secretName: gotify.ing.cert
  rules:
    - host: gotify.{hostname}
      http:
        paths:
          - backend:
              service:
                name: gotify
                port:
                  number: 3000
            path: /
            pathType: Prefix
