apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-ext
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization "Bearer {{BEARER}}";
  labels:
    type: external
    authentified: "true"
spec:
  tls:
    - hosts:
        - headlamp.{hostname}
      secretName: headlamp.ing.cert
  rules:
    - host: headlamp.{hostname}
      http:
        paths:
          - backend:
              service:
                name: headlamp
                port:
                  number: 80
            path: /
            pathType: Prefix
