apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jdownloader-cm.yaml
  - jdownloader-secret.yaml
  - jdownloader-sts.yaml
  - jdownloader-pv.yaml
  - jdownloader-pvc.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
