apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
spec:
  storageClassName: ''
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: vaultwarden
