apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gmusicuploader-deploy.yaml
  - gmusicuploader-secret.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
