apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: aria2-ext
  labels:
    authentified: "true"
    type: external
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - aria2.former-hostname.com
      secretName: aria2.former-hostname.com
  rules:
    - host: aria2.former-hostname.com
      http:
        paths:
          - backend:
              serviceName: aria2
              servicePort: 80
            path: /
          - backend:
              serviceName: aria2
              servicePort: 6800
            path: /jsonrpc