apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aria2-ext
  labels:
    authentified: "true"
    type: external
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - aria2.former-hostname.com
      secretName: aria2.former-hostname.com
  rules:
    - host: aria2.former-hostname.com
      http:
        paths:
          - backend:
              service:
                name: aria2
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: aria2
                port:
                  number: 6800
            path: /jsonrpc
            pathType: Exact
