FROM redwid/aria2-ng:1.1.4

# https://registry.hub.docker.com/r/redwid/aria2-ng
# https://github.com/Redwid/docker-aria2-ng

ADD ./on-dl-finish.sh /usr/bin/on-dl-finish
RUN chmod +x /usr/bin/on-dl-finish