apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- aria2-cm.yaml
- aria2-ext-ing.yaml
- aria2-local-ing.yaml
- aria2-pvc.yaml
- aria2-pv.yaml
- aria2-secret.yaml
- aria2-sts.yaml
- aria2-svc.yaml
patches:
- path: ../../overlays/pv-node-affinity.yaml
  target:
    kind: PersistentVolume
- path: ../../overlays/ing-authentified.yaml
  target:
    kind: Ingress
    labelSelector: authentified
- path: ../../overlays/ing-external.yaml
  target:
    kind: Ingress
    labelSelector: type=external
- path: ../../overlays/ing-local.yaml
  target:
    kind: Ingress
    labelSelector: type=local
transformers:
  - ../../global/ingress-domain-transformer-secret.yaml