apiVersion: batch/v1
kind: CronJob
metadata:
  name: enedis-tracker
spec:
  concurrencyPolicy: Forbid
  schedule: "0 8,14,22 * * *" # Everyday at 8am
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: enedis-tracker
              image: localhost:32000/enedis-tracker
              args:
                - "daily"
              env:
                - name: GOTIFY_URL
                  value: http://$(GOTIFY_SERVICE_HOST):$(GOTIFY_SERVICE_PORT)
              envFrom:
                - secretRef:
                    name: s3-secret
                - secretRef:
                    name: enedis-tracker-secret