apiVersion: batch/v1
kind: CronJob
metadata:
  name: enedis-tracker
spec:
  concurrencyPolicy: Forbid
  schedule: "0 8,14,22 * * *" # Everyday at 8am
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: enedis-tracker
              image: localhost:32000/enedis-tracker
              args:
                - "daily"
              env:
                - name: USAGE_POINT_ID
                  valueFrom:
                    secretKeyRef:
                      name: enedis-tracker-secret
                      key: usage-point-id
                - name: GOTIFY_URL
                  value: http://$(GOTIFY_SERVICE_HOST):$(GOTIFY_SERVICE_PORT)
                - name: GOTIFY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: enedis-tracker-secret
                      key: gotify-token
              envFrom:
                - secretRef:
                    name: s3-secret
          volumes:
            - name: enedis-tracker-secret
              secret:
                secretName: enedis-tracker-secret
