apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gerbera-cm.yaml
- gerbera-deploy.yaml
- gerbera-pvc.yaml
- gerbera-pv.yaml
patches:
- path: ../../overlays/pv-node-affinity.yaml
  target:
    kind: PersistentVolume