apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - emby-deploy.yaml
  - emby-ext-ing.yaml
  - emby-local-ing.yaml
  - emby-pvc.yaml
  - emby-pv.yaml
  - emby-svc.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
  - path: ../../overlays/ing-external.yaml
    target:
      kind: Ingress
      labelSelector: type=external
  - path: ../../overlays/ing-local.yaml
    target:
      kind: Ingress
      labelSelector: type=local
transformers:
  - ../../global/ingress-domain-transformer-secret.yaml