apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-server-cm
data:
  99-ssh-server.conf: |
    PasswordAuthentication no
    PubkeyAuthentication yes
    KbdInteractiveAuthentication no
    PermitRootLogin no
    AllowUsers ssh
    AllowTcpForwarding yes
    GatewayPorts clientspecified
    PermitListen *:1080
    AuthorizedKeysFile .ssh/authorized_keys
