apiVersion: batch/v1
kind: CronJob
metadata:
  name: wallet-monitor
spec:
  concurrencyPolicy: Forbid
  schedule: "5 17 * * 1,2,3,4,5" # 17h05 except weekend
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: wallet-monitor
              image: localhost:32000/wallet-monitor
              env:
                - name: GOTIFY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: wallet-monitor-secret
                      key: gotify-token
                - name: ALPHAVANTAGE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wallet-monitor-secret
                      key: alphavantage-api-key
                - name: GOTIFY_URL
                  value: http://$(GOTIFY_SERVICE_HOST):$(GOTIFY_SERVICE_PORT)
              envFrom:
                - secretRef:
                    name: s3-secret
          volumes:
            - name: wallet-monitor-secret
              secret:
                secretName: wallet-monitor-secret
