apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome-local

  labels:
    type: local
spec:
  rules:
    - host: navidrome.local
      http:
        paths:
          - backend:
              service:
                name: navidrome
                port:
                  number: 4533
            path: /
            pathType: Prefix
