apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/navidrome
