apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  local:
    path: /data/navidrome
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node-name
  claimRef:
    namespace: default
    name: navidrome
