apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
        - name: navidrome
          image: localhost:32000/navidrome
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: public
              subPath: music
              mountPath: /music
              readOnly: true
            - name: navidrome
              subPath: data
              mountPath: /data
          env:
            - name: ND_SCANINTERVAL
              value: 10m
            - name: ND_AUTOIMPORTPLAYLISTS
              value: "false"
            - name: ND_UIWELCOMEMESSAGE
              value: "Bienvenue sur le serveur musical de Babardo !"
            - name: ND_SESSIONTIMEOUT
              value: 8760h
      volumes:
        - name: public
          persistentVolumeClaim:
            claimName: public
        - name: navidrome
          persistentVolumeClaim:
            claimName: navidrome
