apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- boursorama-tracker-cj.yaml
- boursorama-tracker-secret.yaml
patches:
- path: ../../overlays/pv-node-affinity.yaml
  target:
    kind: PersistentVolume