from jameseckersall/sabnzbd:0.7.0
# https://github.com/jameseck/docker-sabnzbd/blob/master/Dockerfile
# https://hub.docker.com/r/jameseckersall/sabnzbd

VOLUME /config /downloads /logs /watchdir /downloads_temp

