apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd
  labels:
    type: local
spec:
  capacity:
    storage: 400Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/sabnzbd
