apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sabnzbd-ext
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    type: external
    authentified: "true"
spec:
  tls:
    - hosts:
        - sabnzbd.former-hostname.com
      secretName: sabnzbd.former-hostname.com
  rules:
    - host: sabnzbd.former-hostname.com
      http:
        paths:
          - backend:
              serviceName: sabnzbd
              servicePort: 80
            path: /
