apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd-local

  labels:
    type: local
spec:
  rules:
    - host: sabnzbd.local
      http:
        paths:
          - backend:
              service:
                name: sabnzbd
                port:
                  number: 80
            path: /
            pathType: Prefix
