apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd
spec:
  storageClassName: ''
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  volumeName: sabnzbd
