apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radio-autoplaylist
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
