apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - samba-deploy.yaml
  - samba-secret.yaml
  - samba-svc.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
