apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      hostNetwork: true
      containers:
        - name: samba
          image: 127.0.0.1:32000/samba
          args:
            - -u
            - "$(SAMBA_USR);$(SAMBA_PWD)"
            - -g #https://github.com/dperson/samba/issues/81
            - "ntlm auth = yes"
            - -s
            - "downloads;/downloads;yes;no;yes;vincent"
            - -s
            - "public;/public;yes;no;yes;vincent"
            - -s
            - "perso;/perso;yes;no;no;vincent"
            - -p
            - -n
          # browsable;readonly;guest
          env:
            - name: SAMBA_USR
              valueFrom:
                secretKeyRef:
                  name: samba-secret
                  key: username
            - name: SAMBA_PWD
              valueFrom:
                secretKeyRef:
                  name: samba-secret
                  key: password
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 500Mi
          livenessProbe:
            tcpSocket:
              port: 445
          readinessProbe:
            tcpSocket:
              port: 445
          ports:
            - containerPort: 139
            - containerPort: 445
            # NMBD
            - containerPort: 137
              protocol: UDP
            - containerPort: 138
          volumeMounts:
            - name: qbitorrent
              subPath: downloads
              mountPath: /downloads/torrent
            - name: sabnzbd
              subPath: downloads
              mountPath: /downloads/sabnzbd
            - name: jdownloader
              subPath: downloads
              mountPath: /downloads/jdownloader
            - name: perso
              mountPath: /perso
            - name: public
              mountPath: /public
            - name: qbitorrent
              subPath: watchdir
              mountPath: /downloads/watchdir/torrent
            - name: sabnzbd
              subPath: watchdir
              mountPath: /downloads/watchdir/nzb
      volumes:
        - name: qbitorrent
          persistentVolumeClaim:
            claimName: qbitorrent
        - name: sabnzbd
          persistentVolumeClaim:
            claimName: sabnzbd
        - name: perso
          persistentVolumeClaim:
            claimName: perso
        - name: public
          persistentVolumeClaim:
            claimName: public
        - name: jdownloader
          persistentVolumeClaim:
            claimName: jdownloader
