apiVersion: v1
kind: Service
metadata:
  name: samba
spec:
  selector:
    app: samba
  type: ClusterIP
  ports: 
  - name: samba-netbios-ssn
    protocol: TCP
    port: 139
    targetPort: 139
  - name: samba-microsoft-ds
    protocol: TCP
    port: 445
    targetPort: 445
  # - name: samba-netbios-ns
  #   protocol: UDP
  #   port: 137
  #   targetPort: 137
  # - name: samba-netbios-dgm
  #   protocol: UDP
  #   port: 138
  #   targetPort: 138