apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
        - name: samba
          image: 127.0.0.1:32000/samba
          args:
            - -u
            - "$(SAMBA_USR);$(SAMBA_PWD)"
            - -g #https://github.com/dperson/samba/issues/81
            - "ntlm auth = yes"
            - -s
            - "downloads;/downloads;yes;no;yes;$(SAMBA_USR)"
            - -s
            - "public;/public;yes;no;yes;$(SAMBA_USR)"
            - -s
            - "perso;/perso;yes;no;no;$(SAMBA_USR)"
            - -p
          # browsable;readonly;guest
          env:
            - name: SAMBA_USR
              valueFrom:
                secretKeyRef:
                  name: samba-secret
                  key: username
            - name: SAMBA_PWD
              valueFrom:
                secretKeyRef:
                  name: samba-secret
                  key: password
            - name: USERID
              value: "0"
            - name: GROUPID
              value: "0"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 500Mi
          livenessProbe:
            tcpSocket:
              port: 445
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: 445
          ports:
            - containerPort: 139
              protocol: TCP
            - containerPort: 445
              protocol: TCP
          #   # NMBD
          #   - containerPort: 137
          #     protocol: UDP
          #   - containerPort: 138
          #     protocol: UDP
          volumeMounts:
            - name: transmission
              subPath: downloads
              mountPath: /downloads/torrent
            - name: sabnzbd
              subPath: downloads
              mountPath: /downloads/sabnzbd
            - name: aria2
              subPath: downloads
              mountPath: /downloads/aria2
            - name: perso
              mountPath: /perso
            - name: public
              mountPath: /public
            - name: transmission
              subPath: watchdir
              mountPath: /downloads/watchdir/torrent
            - name: sabnzbd
              subPath: watchdir
              mountPath: /downloads/watchdir/nzb
      volumes:
        - name: transmission
          persistentVolumeClaim:
            claimName: transmission
        - name: sabnzbd
          persistentVolumeClaim:
            claimName: sabnzbd
        - name: perso
          persistentVolumeClaim:
            claimName: perso
        - name: public
          persistentVolumeClaim:
            claimName: public
        - name: aria2
          persistentVolumeClaim:
            claimName: aria2
