apiVersion: v1
kind: Service
metadata:
  name: samba
  annotations:
    metallb.io/allow-shared-ip: main-node-vip
spec:
  selector:
    app: samba
  type: LoadBalancer
  loadBalancerIP: 192.168.1.200
  ports:
    - name: samba-netbios-ssn
      protocol: TCP
      port: 139
      targetPort: 139
    - name: samba-microsoft-ds
      protocol: TCP
      port: 445
      targetPort: 445