apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - radio-autoplaylist-frontend-secret.yaml
  - radio-autoplaylist-frontend-deploy.yaml
  - radio-autoplaylist-frontend-svc.yaml
  - radio-autoplaylist-frontend-ext-ing.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
  - path: ../../overlays/ing-authentified.yaml
    target:
      kind: Ingress
      labelSelector: authentified
  - path: ../../overlays/ing-external.yaml
    target:
      kind: Ingress
      labelSelector: type=external
  - path: ../../overlays/ing-local.yaml
    target:
      kind: Ingress
      labelSelector: type=local
transformers:
  - ../../global/ingress-domain-transformer-secret.yaml