apiVersion: v1
data:
  s3-to-influx-conf.yaml: |+
    inputs:
      - type: daily
        s3:
          bucket: wallet-monitor
          path: "daily_wallets/{day}.json"
        content:
          items_key: wallet
        influx:
          bucket: my-data
          measurement: wallet_daily
          time:
            path: "request.Key"
            fns: ["s3_key_to_day"]
          tags:
            - path: isin
              name: isin
            - path: price.currency
              name: amountCurrency
          fields:
            - path: targetRatio
              name: targetRatio
              fns: ["float"]
            - path: qtyOwned
              name: qtyOwned
            - path: price.amount
              name: stockPrice
              fns: ["float"]
      - type: daily
        s3:
          bucket: enedis-tracker
          path: "{env.ENEDIS_USAGE_POINT_ID}/daily_consumption/{day}.json"
        influx:
          bucket: my-data
          measurement: enedis_daily
          time:
            path: "request.Key"
            fns: ["s3_key_to_day"]
          tags:
            - path: usagePointId
              name: usagePointId
            - path: unit
              name: unit
          fields:
            - path: value
              name: consumption
      - type: daily
        s3:
          bucket: boursorama-tracker
          path: "movements/{env.BOURSO_ACCOUNT_ID}/{day}.json"
        influx:
          bucket: my-data
          measurement: boursorama-expenses
          allow_duplicates: true
          time:
            path: dateOp
          tags:
            - path: label
              name: label
            - path: category
              name: category
            - path: categoryParent
              name: categoryParent
            - path: comment
              name: comment
            - path: accountNum
              name: accountNum
            - path: accountLabel
              name: accountLabel
          fields:
            - path: amount
              name: amount
              fns: ["float"]
            - path: accountBalance
              name: accountBalance
              fns: ["float_nullable"]
      - type: daily
        s3:
          bucket: woob-extractor
          path: "bp/accounts/{day}.csv"
        influx:
          bucket: my-data
          measurement: bp-accounts
          time:
            path: "request.Key"
            fns: ["s3_key_to_day"]
          tags:
            - path: id
              name: accountNumber
            - path: label
              name: label
            - val: eur
              name: currency
            - path: type
              name: type
          fields:
            - path: balance
              name: balance
              fns: ["float"]
            - path: coming
              name: coming
              fns: ["float_nullable"]
      - type: daily
        s3:
          bucket: woob-extractor
          path: "bp/history/{env.BP_MAIN_ACCOUNT_ID}/{day}.csv"
        influx:
          bucket: my-data
          measurement: bp-history
          allow_duplicates: true
          time:
            path: "request.Key"
            fns: ["s3_key_to_day"]
          tags:
            - path: label
              name: label
            - path: type
              name: type
          fields:
            - path: amount
              name: amount
              fns: ["float"]
      - type: daily
        s3:
          bucket: woob-extractor
          path: "bd/investment/{env.BD_MAIN_ACCOUNT_ID}/{day}.csv"
        influx:
          bucket: my-data
          measurement: bd-investment
          time:
            path: "request.Key"
            fns: ["s3_key_to_day"]
          tags:
            - path: label
              name: label
            - path: code
              name: code
            - path: code_type
              name: code_type
          fields:
            - path: quantity
              name: quantity
              fns: ["int"]
              skip_when: ["code", "eq", "XX-liquidity"]
            - path: unitprice
              name: unitprice
              fns: ["float"]
              skip_when: ["code", "eq", "XX-liquidity"]
            - path: unitvalue
              name: unitvalue
              fns: ["float"]
              skip_when: ["code", "eq", "XX-liquidity"]
            - path: valuation
              name: valuation
              fns: ["float"]
            - path: diff
              name: diff
              fns: ["float"]
              skip_when: ["code", "eq", "XX-liquidity"]
            - path: portfolio_share
              name: portfolio_share
              fns: ["float"]
              skip_when: ["code", "eq", "XX-liquidity"]
      - type: daily
        s3:
          bucket: woob-extractor
          path: "bd/history/{env.BD_MAIN_ACCOUNT_ID}/{day}.csv"
        influx:
          bucket: my-data
          measurement: bd-history
          allow_duplicates: true
          time:
            path: "request.Key"
            fns: ["s3_key_to_day"]
          tags:
            - path: label
              name: label
            - path: type
              name: type
          fields:
            - path: amount
              name: amount
              fns: ["float"]
kind: ConfigMap
metadata:
  name: s3-to-influxdb
