apiVersion: v1
kind: PersistentVolume
metadata:
  name: rclone-perso
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  local:
    path: /data/rclone-perso
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vincent
  claimRef:
    namespace: default
    name: rclone-perso
