apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone-perso
spec:
  storageClassName: ''
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: rclone-perso
