apiVersion: v1
kind: PersistentVolume
metadata:
  name: rclone-perso
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/rclone-perso
