apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-server-ext
  labels:
    type: external
spec:
  tls:
    - hosts:
        - serve.{hostname}
      secretName: serve.ing.cert
  rules:
    - host: serve.{hostname}
      http:
        paths:
          - backend:
              service:
                name: http-server
                port:
                  number: 3000
            path: /
            pathType: Prefix
