apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: http-server
          image: localhost:32000/http-server
          ports:
            - name: http-server
              containerPort: 3000
          volumeMounts:
            - name: public
              subPath: serve
              mountPath: /var/www
            - name: config
              subPath: nginx.conf
              mountPath: /etc/nginx/nginx.conf
          livenessProbe:
            httpGet:
              path: /.health
              port: http-server
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /.health
              port: http-server
              scheme: HTTP
      volumes:
        - name: public
          persistentVolumeClaim:
            claimName: public
        - name: config
          configMap:
            name: http-server
            items:
              - key: nginx.conf
                path: nginx.conf
