apiVersion: v1
data:
  nginx.conf: |
    worker_processes  2;

    pid logs/nginx.pid;
    load_module "modules/ngx_http_fancyindex_module.so";

    events {
    }

    http {
        # default set of files and their content types
        include      mime.types;
        # prompt user for download for any undeclared file format
        default_type application/octet-stream;
        # optimization when serving static files
        sendfile     on;
        
        server {
            listen 3000;

            server_name localhost serve.*;
            
            location / {
                root   /var/www/;
                index  index.html index.htm;
                gzip_static off;

                fancyindex on;
                fancyindex_localtime on;
                fancyindex_exact_size off;

                # https://github.com/drklee3/Nginx-Fancyindex-Minimal
                fancyindex_header "/.theme/header.html";
                fancyindex_footer "/.theme/footer.html";
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: http-server
