apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "*"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.1.0/24"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
