apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "*"
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-nginx-secret
