apiVersion: v1
kind: PersistentVolume
metadata:
  name: "*"
  labels:
    type: local
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - brix-vincent
