FROM influxdb:2.3.0-alpine

# https://hub.docker.com/_/influxdb
# https://github.com/influxdata/influxdata-docker/blob/491959043fe4ad691cb6d7a6df6c1a48ee51723d/influxdb/1.8/alpine/Dockerfile

ADD ./init.sh /init.sh 
RUN chmod +x /init.sh