apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb-local

  labels:
    type: local
spec:
  rules:
    - host: influxdb.local
      http:
        paths:
          - backend:
              service:
                name: home-assistant
                port:
                  number: 8086
            path: /
            pathType: Prefix