apiVersion: v1
data:
  configuration.yaml: |+
    homeassistant: true
    permit_join: true
    mqtt:
      base_topic: zigbee2mqtt
      server: mqtt://localhost:1883
      include_device_information: true
    serial:
      port: /dev/ttyACM0
      adapter: zstack
    advanced:
      homeassistant_legacy_entity_attributes: false
      legacy_api: false
      legacy_availability_payload: false
      log_level: debug
      channel: 15
    device_options:
      legacy: false
    frontend: true
    devices: devices.yaml
    groups: groups.yaml
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: zigbee2mqtt
