apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt
spec:
  storageClassName: ''
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: zigbee2mqtt
