apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mosquitto
