apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - slurp-news-deploy.yaml
  - slurp-news-ext-ing.yaml
  - slurp-news-local-ing.yaml
  - slurp-news-pvc.yaml
  - slurp-news-pv.yaml
  - slurp-news-secret.yaml
  - slurp-news-svc.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
  - path: ../../overlays/ing-authentified.yaml
    target:
      kind: Ingress
      labelSelector: authentified
  - path: ../../overlays/ing-external.yaml
    target:
      kind: Ingress
      labelSelector: type=external
  - path: ../../overlays/ing-local.yaml
    target:
      kind: Ingress
      labelSelector: type=local
transformers:
  - ../../global/ingress-domain-transformer-secret.yaml