apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - wallabag-deploy.yaml
  - wallabag-svc.yaml
  - wallabag-pvc.yaml
  - wallabag-pv.yaml
  - wallabag-secret.yaml
  - wallabag-ext-ing.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
  - path: ../../overlays/ing-authentified.yaml
    target:
      kind: Ingress
      labelSelector: authentified
  - path: ../../overlays/ing-external.yaml
    target:
      kind: Ingress
      labelSelector: type=external
  - path: ../../overlays/ing-local.yaml
    target:
      kind: Ingress
      labelSelector: type=local
