apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - attestation-deploy.yaml
  - attestation-ext-ing.yaml
  - attestation-secret.yaml
  - attestation-svc.yaml
patches:
  - path: ../../overlays/ing-authentified.yaml
    target:
      kind: Ingress
      labelSelector: authentified
  - path: ../../overlays/ing-external.yaml
    target:
      kind: Ingress
      labelSelector: type=external
