apiVersion: apps/v1
kind: Deployment
metadata:
  name: edith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edith
  template:
    metadata:
      labels:
        app: edith
    spec:
      initContainers:
        - name: edith-init
          image: busybox
          command: ["/bin/sh", "-c", "chmod 777 -R /opt/"]
          volumeMounts:
            - name: perso
              subPath: pad
              mountPath: /opt/
      containers:
        - name: edith
          image: localhost:32000/edith
          ports:
            - containerPort: 80
          volumeMounts:
            - name: perso
              subPath: pad
              mountPath: /app/data
      volumes:
        - name: perso
          persistentVolumeClaim:
            claimName: perso