apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - edith-deploy.yaml
  - edith-ext-ing.yaml
  - edith-local-ing.yaml
  - edith-svc.yaml
patches:
  - path: ../../overlays/ing-authentified.yaml
    target:
      kind: Ingress
      labelSelector: authentified
  - path: ../../overlays/ing-external.yaml
    target:
      kind: Ingress
      labelSelector: type=external
  - path: ../../overlays/ing-local.yaml
    target:
      kind: Ingress
      labelSelector: type=local
transformers:
  - ../../global/ingress-domain-transformer-secret.yaml