FROM boypt/cloud-torrent:1.2.6
# https://github.com/boypt/simple-torrent/blob/master/Dockerfile
# https://hub.docker.com/r/boypt/cloud-torrent/tags

VOLUME /watchdir /downloads

EXPOSE 3000

ENTRYPOINT ["cloud-torrent"]