apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - slurp-lemonde-deploy.yaml
  - slurp-lemonde-ext-ing.yaml
  - slurp-lemonde-local-ing.yaml
  - slurp-lemonde-pvc.yaml
  - slurp-lemonde-pv.yaml
  - slurp-lemonde-secret.yaml
  - slurp-lemonde-svc.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
  - path: ../../overlays/ing-authentified.yaml
    target:
      kind: Ingress
      labelSelector: authentified
  - path: ../../overlays/ing-external.yaml
    target:
      kind: Ingress
      labelSelector: type=external
  - path: ../../overlays/ing-local.yaml
    target:
      kind: Ingress
      labelSelector: type=local
