apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
spec:
  storageClassName: ''
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: home-assistant
