apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- home-assistant-sts.yaml
- home-assistant-local-ing.yaml
- home-assistant-ext-ing.yaml
- home-assistant-pvc.yaml
- home-assistant-pv.yaml
- home-assistant-svc.yaml
- home-assistant-cm.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
  - path: ../../overlays/ing-authentified.yaml
    target:
      kind: Ingress
      labelSelector: authentified
  - path: ../../overlays/ing-external.yaml
    target:
      kind: Ingress
      labelSelector: type=external
  - path: ../../overlays/ing-local.yaml
    target:
      kind: Ingress
      labelSelector: type=local
transformers:
  - ../../global/ingress-domain-transformer-secret.yaml