apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - woob-extractor-cj.yaml
  - woob-extractor-cm.yaml
  - woob-extractor-secret.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
