apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: upload-ext
  labels:
    type: external
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  tls:
    - hosts:
        - upload.former-hostname.com
      secretName: upload.former-hostname.com
  rules:
    - host: upload.former-hostname.com
      http:
        paths:
          - backend:
              serviceName: upload
              servicePort: 8080
            path: /
