apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upload-local
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  labels:
    type: local
spec:
  rules:
    - host: upload.local
      http:
        paths:
          - backend:
              service:
                name: upload
                port:
                  number: 8080
            path: /
            pathType: Prefix
