apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upload-ext
  labels:
    type: external
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  tls:
    - hosts:
        - upload.{hostname}
      secretName: upload.ing.cert
  rules:
    - host: upload.{hostname}
      http:
        paths:
          - backend:
              service:
                name: upload
                port:
                  number: 8080
            path: /
            pathType: Prefix
