apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minidlna-cm.yaml
  - minidlna-deploy.yaml
patches:
  - path: ../../overlays/pv-node-affinity.yaml
    target:
      kind: PersistentVolume
