apiVersion: v1
kind: PersistentVolume
metadata:
  name: minidlna
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    # the volume can be mounted as read-write by many nodes
    - ReadWriteMany
    # Allow WaitForFirstConsumer
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/minidlna
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node-name
  claimRef:
    namespace: default
    name: minidlna
