apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ddns-updater-local
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    type: local
spec:
  rules:
    - host: ddns.local
      http:
        paths:
          - backend:
              serviceName: ddns-updater
              servicePort: 8000
            path: /
