apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ddns-updater-ext

  labels:
    type: external
    authentified: "true"
spec:
  tls:
    - hosts:
        - ddns.former-hostname.com
      secretName: ddns.former-hostname.com
  rules:
    - host: ddns.former-hostname.com
      http:
        paths:
          - backend:
              service:
                name: ddns-updater
                port:
                  number: 8000
            path: /
            pathType: Prefix
