apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - telegraf-clusterrolebinding.yaml
  - telegraf-clusterrole.yaml
  - telegraf-cm.yaml
  - telegraf-ds.yaml
  - telegraf-sa.yaml
  - telegraf-secret.yaml
