apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf
  labels:
    app.kubernetes.io/name: telegraf
subjects:
  - kind: ServiceAccount
    name: telegraf
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegraf