FROM linuxserver/qbittorrent:4.3.0202003210718-6893-f44f1ffubuntu18.04.1-ls27
# https://hub.docker.com/r/linuxserver/qbittorrent/tags
# https://github.com/linuxserver/docker-qbittorrent

ADD ./notify-finished.sh /usr/bin/notify-finished
RUN chmod +x /usr/bin/notify-finished