apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall-ext
  labels:
    type: external

spec:
  tls:
    - hosts:
        - former-hostname.com
      secretName: former-hostname.com
  rules:
    - host: former-hostname.com
      http:
        paths:
          - backend:
              service:
                name: heimdall
                port:
                  number: 80
            path: /
            pathType: Prefix
