apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: heimdall-local
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    type: local
spec:
  rules:
    - host: heimdall.local
      http:
        paths:
          - backend:
              serviceName: heimdall
              servicePort: 80
            path: /
