apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/heimdall
