name: Push To Public Repo

on:
  push:
    branches: master

concurrency: 1


jobs:
  build:
    name: Push / deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          ls -al
          ./scripts/rm-repo-secrets.sh