name: Push To Public Repo

on:
  push:
    branches: master

concurrency: 1


jobs:
  build:
    name: Push / deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          ./scripts/rm-repo-secrets.sh
           git remote add public-repo git@github.com:v-garcia/home-server.git
           git push  public-repo master --force